// flow-typed signature: 1f7c683d1e533c985e09d10e67e01b6c
// flow-typed version: <<STUB>>/@types/chalk_v^0.4.31/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chalk' {
  declare module.exports: any;
}
