// flow-typed signature: 09a5a5ab2a24a207c4d7d11151c0c147
// flow-typed version: <<STUB>>/@types/chalk_v^0.4.30

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chalk' {
  declare module.exports: any;
}
