// flow-typed signature: 83fa8694934a5d69c44726aff4e4ccb7
// flow-typed version: <<STUB>>/@types/chalk_v^0.4.30/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chalk' {
  declare module.exports: any;
}
