// flow-typed signature: 596c1d5e74d74003ae184a74474253f9
// flow-typed version: <<STUB>>/@types/configstore_v^0.3.30

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/configstore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/configstore' {
  declare module.exports: any;
}
