// flow-typed signature: f3e268bf091f157f6d4e82e4e6d0f645
// flow-typed version: <<STUB>>/@types/configstore_v^0.3.30/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/configstore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/configstore' {
  declare module.exports: any;
}
