// flow-typed signature: 4a0e208fc39a6177fb3b00056a84c04e
// flow-typed version: <<STUB>>/@types/he_v^0.5.29/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/he'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/he' {
  declare module.exports: any;
}
