// flow-typed signature: a92c3ec380a7d27de0a7cadf7f054b17
// flow-typed version: <<STUB>>/@types/he_v^0.5.29

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/he'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/he' {
  declare module.exports: any;
}
