// flow-typed signature: 9ee3e955d69c3f8def97d566cd636867
// flow-typed version: <<STUB>>/@types/inquirer_v^0.0.29

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/inquirer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/inquirer' {
  declare module.exports: any;
}
