// flow-typed signature: 8caff8a7fb9cb197ddaebd7c53e27cb0
// flow-typed version: <<STUB>>/@types/ora_v^0.0.29/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/ora'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/ora' {
  declare module.exports: any;
}
