// flow-typed signature: 0cdf44d7208306ded1ac4e299fedc9a3
// flow-typed version: <<STUB>>/@types/ora_v^0.3.31/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/ora'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/ora' {
  declare module.exports: any;
}
