// flow-typed signature: 41b77683a82430369eee10dcd7a9c110
// flow-typed version: <<STUB>>/@types/ora_v^0.0.29

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/ora'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/ora' {
  declare module.exports: any;
}
