// flow-typed signature: 5fdf4f2b8ce56163fde19984f8c6f81d
// flow-typed version: <<STUB>>/@types/path-exists_v^1.0.29

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/path-exists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/path-exists' {
  declare module.exports: any;
}
