// flow-typed signature: a8cbebc74e9bf944ee8a6bf2314b90d8
// flow-typed version: <<STUB>>/@types/path-exists_v^1.0.29/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/path-exists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/path-exists' {
  declare module.exports: any;
}
