// flow-typed signature: db47a63cde3e7faf97d26cfd0cb1d751
// flow-typed version: <<STUB>>/@types/request_v^0.0.31/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request' {
  declare module.exports: any;
}
