// flow-typed signature: 3286a3a73c809bd5cc35b6149743b7b1
// flow-typed version: <<STUB>>/@types/request-promise_v^3.0.32

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request-promise' {
  declare module.exports: any;
}
