// flow-typed signature: e729a780941b063113686ce3e5927ad2
// flow-typed version: <<STUB>>/@types/request-promise_v^4.1.33/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request-promise' {
  declare module.exports: any;
}
