// flow-typed signature: 7f8b3ec2eeca7751cd8faf02b4acfce9
// flow-typed version: <<STUB>>/@types/request_v^0.0.31

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/request' {
  declare module.exports: any;
}
