// flow-typed signature: b14b2e71cb0960d984500fdab838788a
// flow-typed version: <<STUB>>/@types/update-notifier_v^0.0.28/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/update-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/update-notifier' {
  declare module.exports: any;
}
