// flow-typed signature: a1d97da4a48ac77deda7fb412e8997c7
// flow-typed version: <<STUB>>/@types/update-notifier_v^0.0.29/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/update-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/update-notifier' {
  declare module.exports: any;
}
