// flow-typed signature: 4ac7403b96add0cc90d5f3c1be852e3b
// flow-typed version: <<STUB>>/@types/update-notifier_v^0.0.28

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/update-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/update-notifier' {
  declare module.exports: any;
}
