// flow-typed signature: b5cf947e5f1eda0bdc5b74861a35dea8
// flow-typed version: <<STUB>>/@types/yargs_v^0.0.33

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/yargs' {
  declare module.exports: any;
}
