// flow-typed signature: 882a13aed39ac0da8f793ceceed17b46
// flow-typed version: <<STUB>>/@types/yargs_v^0.0.33/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/yargs' {
  declare module.exports: any;
}
