// flow-typed signature: 0720b8a33f21a822dec61acf21b061a7
// flow-typed version: <<STUB>>/browser-id3-writer_v^2.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-id3-writer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-id3-writer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-id3-writer/dist/browser-id3-writer' {
  declare module.exports: any;
}

declare module 'browser-id3-writer/dist/browser-id3-writer.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-id3-writer/dist/browser-id3-writer.js' {
  declare module.exports: $Exports<'browser-id3-writer/dist/browser-id3-writer'>;
}
declare module 'browser-id3-writer/dist/browser-id3-writer.min.js' {
  declare module.exports: $Exports<'browser-id3-writer/dist/browser-id3-writer.min'>;
}
