// flow-typed signature: 76bb3abc597f6ccc86df7be8c8589b93
// flow-typed version: <<STUB>>/configstore_v^2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'configstore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'configstore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'configstore/index' {
  declare module.exports: $Exports<'configstore'>;
}
declare module 'configstore/index.js' {
  declare module.exports: $Exports<'configstore'>;
}
