// flow-typed signature: 6c13213acb69421cc761a94c9f507963
// flow-typed version: <<STUB>>/email-regex_v^1.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'email-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'email-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'email-regex/index' {
  declare module.exports: $Exports<'email-regex'>;
}
declare module 'email-regex/index.js' {
  declare module.exports: $Exports<'email-regex'>;
}
