// flow-typed signature: fbcbb58fc330b30124e2b5ea7a04bae6
// flow-typed version: <<STUB>>/ipics_v^1.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ipics/index' {
  declare module.exports: $Exports<'ipics'>;
}
declare module 'ipics/index.js' {
  declare module.exports: $Exports<'ipics'>;
}
