// flow-typed signature: 8a4dc6b87e16a8cce27624371f41744c
// flow-typed version: <<STUB>>/request-progress_v^3.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-progress/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-progress/index' {
  declare module.exports: $Exports<'request-progress'>;
}
declare module 'request-progress/index.js' {
  declare module.exports: $Exports<'request-progress'>;
}
declare module 'request-progress/test/test.js' {
  declare module.exports: $Exports<'request-progress/test/test'>;
}
